### ISSUE TITLE
Allow for custom price API

### ISSUE THREAD

**Issue by junderw** [lightninglabs/faraday#113]
If the price API interface is simple enough, we'd like to implement it and use our exchange's data to price the data in the audits.

1. Should be able to select currency other than USD (ie. JPY)
2. Should be able to point the price endpoint to our own API (internal, that supplies historical JPY price data)

**Comment by carlaKC** [comment]
Thanks for the issue! 

> Should be able to select currency other than USD (ie. JPY)

Should be addressed by #115 !

> Should be able to point the price endpoint to our own API 

There are two ways we could go about expanding the way that faraday gets fiat prices.
1. Add your exchange's API to the backend options that faraday offers, as in #116
2. Add an option to run the various fiat endpoints with imported price data. Eg, you'd run the `nodeaudit` command and just point it to a CSV which has timestamp/price values for your relevant range. 

I'm open to both of these options. I think that (2) has some advantages because it provides a generic path forward for use of your own price data, whatever that may be. What are your thoughts on this @junderw ?

**Comment by junderw** [comment]
2 definitely seems easier to maintain on your end and we'd be fine with it.
The CSV format and behavior would need to be well defined.

**Comment by carlaKC** [comment]
> 2 definitely seems easier to maintain on your end and we'd be fine with it.

Awesome!

I think that it would just need to be the following: 
- Format: `unix ts seconds, price of 1 btc in currency of choice`
- Range: If working with some range `start` (inclusive) -> `end` (exclusive), we require the first price point to be <= start timestamp

In terms of behaviour, for some transaction that happened at time `ts` we would sort the data and use the timestamp that preceeds `ts`.

For example: given a set of timestamps/prices:
```
100/55k
110/56k
120/54k
```

If we want the price at `ts=115`, we use use the price point at `110/56k`.

**Comment by ellemouton** [comment]
currently working on this
