### ISSUE TITLE
Query on the Minimum Monitored Time of Channels when LND restarts

### ISSUE THREAD

**Issue by 99ytrewq911** [lightninglabs/faraday#31]
It appears the the default amount of seconds for a channel to be monitored before it gets considered by the **outliers** subcommand is 2419200, or 28 days. 

It also appears that if the LND daemon is restarted, that this monitored time is reset back to zero seconds.

I've already had a few kernel updates this month that required system reboots, and the monitored time ended up resetting as expected.

 I guess it would require the operator to monitor the values somewhat frequently (which is okay, this is a lightning node), but values such as uptime ratio still get reset to 0. 

It's possible some operators might never make it to 28 days of uptime either without needing a reboot or service restart of some sort, and they may not run into the --min_monitored command flag.

I set my minimum uptime to ~2-3 days but I am hoping to get insight from other users or devs on a suggested shorter time than 28 days.

Thank you

**Comment by carlaKC** [comment]
The 28 day default was chosen to be intentionally cautious so that people are made aware of the limitation of this number; rather have the inconvenience upfront than close a channel without full understanding of the data you've been presented. 

However, the monitored time being reset certainly isn't ideal in its current incarnation. This will be addressed by lightningnetwork/lnd/issues/4165 in the next major release. Rather fix the root cause than the symptom by changing defaults here?

**Comment by 99ytrewq911** [comment]
That all makes sense to me. Good to see it's on LND's end is getting fixed. Thank you
